xsp = 0
ysp = 0
startx = x
starty = y
respawning = false;       // Are we in the hit/respawn state?
hit_timer = 0;            // Counts the time while paused/fading
hit_duration = 60;        // Duration of effect in frames (1 second at 60 FPS)
original_color = c_white; // We'll use this if you want to restore later
death_x = x;
death_y = y;
death_sprite = 0
death_image = 0
teleport_delay = 60;
sound_playing = false;
death_playing = false;